# Generated by Django 5.2.6 on 2026-02-08 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_livingRoom', '0004_product_details_product_features_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=200)),
                ('product_name', models.CharField(max_length=200)),
                ('variant_name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='cart/')),
                ('new_price', models.IntegerField()),
                ('old_price', models.IntegerField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
