# Generated by Django 5.2.6 on 2026-02-12 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_livingRoom', '0005_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='seater',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
