# Generated by Django 5.2.6 on 2026-02-14 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_livingRoom', '0007_product_image_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
